BACKUP DATABASE S4_Agenda_PEMA
TO DISK = 'D:\MSSQL\Backup\S4_Agenda_PEMA.bak' WITH INIT, NO_COMPRESSION
GO

BACKUP DATABASE S4_Agenda_PEMA_Doc
TO DISK = 'D:\MSSQL\Backup\S4_Agenda_PEMA_Doc.bak' WITH INIT, NO_COMPRESSION
GO

BACKUP DATABASE S4_System
TO DISK = 'D:\MSSQL\Backup\S4_System.bak' WITH INIT, NO_COMPRESSION
GO