BACKUP DATABASE S4_Agenda_PEMA
TO DISK = '\\DBSERVER\Backup\S4_Agenda_PEMA.bak' WITH INIT, NO_COMPRESSION
GO

BACKUP DATABASE S4_System
TO DISK = '\\DBSERVER\Backup\S4_System.bak' WITH INIT, NO_COMPRESSION
GO