IF OBJECT_ID('dbo.USER_S5_Sklady_PohybZasobyPrehled', 'V') IS NOT NULL DROP VIEW dbo.USER_S5_Sklady_PohybZasobyPrehled;
GO

CREATE VIEW dbo.USER_S5_Sklady_PohybZasobyPrehled AS
SELECT Pohyb.ID,
       Pohyb.Parent_ID,
       Pohyb.Root_ID,
       Pohyb.Group_ID,
       Pohyb.Deleted,
       Pohyb.Locked,
       Pohyb.Create_ID,
       Pohyb.Create_Date,
       Pohyb.Modify_ID,
       Pohyb.Modify_Date,
       Pohyb.Hidden,
       Pohyb.Konto_ID,
       Pohyb.Obdobi_ID,
       Pohyb.Datum,
       Doklad.CasSkladovehoPohybu,
	   Doklad.DatumVystaveni,
       Pohyb.DruhPohybu,
       Pohyb.Znamenko,
       Pohyb.JednotkaCena,
       Pohyb.Mnozstvi,
       Pohyb.MnozstviZbyva,
       Pohyb.MnozstviVyrizene,
       Pohyb.CelkovaCena,
       Pohyb.Detail_ID,
       Pohyb.Serie_ID,
       Doklad.ObjectName AS DokladObjectName,
       Pohyb.Doklad_ID,
       Pohyb.Odchylka,
       COALESCE (Polozka.Stredisko_ID,
                 Doklad.Stredisko_ID) AS Stredisko_ID,
                COALESCE (Polozka.Zakazka_ID,
                          Doklad.Zakazka_ID) AS Zakazka_ID,
                         COALESCE (Polozka.Cinnost_ID,
                                   Doklad.Cinnost_ID) AS Cinnost_ID,
                                  CASE
                                      WHEN COALESCE ([Pohyb].[Znamenko],
                                                     0) = COALESCE ([Pohyb].[DruhPohybu],
                                                                    0) THEN [Pohyb].[Mnozstvi]
                                      ELSE - [Pohyb].[Mnozstvi]
                                  END AS MnozstviZ,
                                  CASE
                                      WHEN COALESCE ([Pohyb].[Znamenko],
                                                     0) = COALESCE ([Pohyb].[DruhPohybu],
                                                                    0) THEN [Pohyb].[MnozstviZbyva]
                                      ELSE - [Pohyb].[MnozstviZbyva]
                                  END AS MnozstviZbyvaZ,
                                  CASE
                                      WHEN COALESCE ([Pohyb].[Znamenko],
                                                     0) = COALESCE ([Pohyb].[DruhPohybu],
                                                                    0) THEN [Pohyb].[MnozstviVyrizene]
                                      ELSE - [Pohyb].[MnozstviVyrizene]
                                  END AS MnozstviVyrizeneZ,
                                  CASE
                                      WHEN COALESCE ([Pohyb].[Znamenko],
                                                     0) = COALESCE ([Pohyb].[DruhPohybu],
                                                                    0) THEN [Pohyb].[CelkovaCena]
                                      ELSE - [Pohyb].[CelkovaCena]
                                  END AS CelkovaCenaZ,
                                  Doklad.Mena_ID,
                                  CASE
                                      WHEN COALESCE ([Polozka].[Mnozstvi],
                                                     0) = 0 THEN [Polozka].[DphZakladCM]
                                      ELSE [Polozka].[DphZakladCM] / [Polozka].[Mnozstvi] * COALESCE ([Pohyb].[Mnozstvi],
                                                                                                      0)
                                  END AS DphZakladCM,
                                  CASE
                                      WHEN COALESCE ([Polozka].[Mnozstvi],
                                                     0) = 0 THEN [Polozka].[CelkovaCena]
                                      ELSE [Polozka].[CelkovaCena] / [Polozka].[Mnozstvi] * COALESCE ([Pohyb].[Mnozstvi],
                                                                                                      0)
                                  END AS ProdejniCena,
                                  CASE
                                      WHEN COALESCE ([Polozka].[Mnozstvi],
                                                     0) = 0 THEN [Polozka].[CelkovaCenaCM]
                                      ELSE [Polozka].[CelkovaCenaCM] / [Polozka].[Mnozstvi] * COALESCE ([Pohyb].[Mnozstvi],
                                                                                                        0)
                                  END AS ProdejniCenaCM,
                                  Polozka.JednCena AS ProdejniJednCena,
                                  Polozka.JednCenaCM AS ProdejniJednCenaCM,
                                  Doklad.CisloDokladu,
                                  Doklad.AdresaNazev,
                                  Doklad.Firma_ID,
                                  Polozka.ID AS Polozka_ID,
                                  Polozka.Jednotka,
                                  Polozka.Nazev AS PolozkaNazev,
                                  Polozka.Predkontace_ID,
                                  Polozka.UcetMD_ID,
                                  Polozka.UcetDal_ID,
                                  Doklad.Nazev AS DokladNazev,
                                  Doklad.IC,
                                  Pohyb.NavazujiciPohyb_ID,
                                  CASE
                                      WHEN Pohyb.NavazujiciPohyb_ID = Pohyb.ID THEN 'True'
                                      ELSE 'False'
                                  END AS FiktivniPohyb
FROM dbo.Sklady_PohybZasoby AS Pohyb WITH (NOLOCK)
LEFT OUTER JOIN
  (SELECT ID,
          'SkladovyDoklad' AS ObjectName,
          Stredisko_ID,
          Zakazka_ID,
          Cinnost_ID,
          Mena_ID,
          IC,
          Nazev,
          AdresaNazev,
          Firma_ID,
          CisloDokladu,
          CasSkladovehoPohybu,
          DatumVystaveni
   FROM dbo.SkladovyDoklad_SkladovyDoklad WITH (NOLOCK)
   UNION SELECT ID,
                'DodaciListPrijaty' AS ObjectName,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                Mena_ID,
                IC,
                Nazev,
                AdresaNazev,
                Firma_ID,
                CisloDokladu,
                CasSkladovehoPohybu,
                DatumVystaveni
   FROM dbo.SkladovyDoklad_DodaciListPrijaty WITH (NOLOCK)
   UNION SELECT ID,
                'DodaciListVydany' AS ObjectName,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                Mena_ID,
                IC,
                Nazev,
                AdresaNazev,
                Firma_ID,
                CisloDokladu,
                CasSkladovehoPohybu,
                DatumVystaveni
   FROM dbo.SkladovyDoklad_DodaciListVydany WITH (NOLOCK)
   UNION SELECT ID,
                'ProdejkaPrijata' AS ObjectName,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                Mena_ID,
                IC,
                Nazev,
                AdresaNazev,
                Firma_ID,
                CisloDokladu,
                CasSkladovehoPohybu,
                DatumVystaveni
   FROM dbo.SkladovyDoklad_ProdejkaPrijata WITH (NOLOCK)
   UNION SELECT ID,
                'ProdejkaVydana' AS ObjectName,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                Mena_ID,
                IC,
                Nazev,
                AdresaNazev,
                Firma_ID,
                CisloDokladu,
                CasSkladovehoPohybu,
                DatumVystaveni
   FROM dbo.SkladovyDoklad_ProdejkaVydana WITH (NOLOCK)
   UNION SELECT ID,
                'Vyrobka' AS ObjectName,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                Mena_ID,
                IC,
                Nazev,
                AdresaNazev,
                Firma_ID,
                CisloDokladu,
                CasSkladovehoPohybu,
                DatumVystaveni
   FROM dbo.SkladovyDoklad_Vyrobka WITH (NOLOCK)) AS Doklad ON Doklad.ID = Pohyb.Doklad_ID
LEFT OUTER JOIN
  (SELECT ID,
          'PolozkaSkladovehoDokladu' AS ObjectName,
          Root_ID,
          Nazev,
          Stredisko_ID,
          Zakazka_ID,
          Cinnost_ID,
          DphZakladCM,
          CelkovaCena,
          CelkovaCenaCM,
          JednCena,
          JednCenaCM,
          Mnozstvi,
          Jednotka,
          Predkontace_ID,
          UcetDal_ID,
          UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaSkladovehoDokladu WITH (NOLOCK)
   UNION SELECT ID,
                'PolozkaDodacihoListuPrijateho' AS ObjectName,
                Root_ID,
                Nazev,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                DphZakladCM,
                CelkovaCena,
                CelkovaCenaCM,
                JednCena,
                JednCenaCM,
                Mnozstvi,
                Jednotka,
                Predkontace_ID,
                UcetDal_ID,
                UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaDodacihoListuPrijateho WITH (NOLOCK)
   UNION SELECT ID,
                'PolozkaDodacihoListuVydaneho' AS ObjectName,
                Root_ID,
                Nazev,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                DphZakladCM,
                CelkovaCena,
                CelkovaCenaCM,
                JednCena,
                JednCenaCM,
                Mnozstvi,
                Jednotka,
                Predkontace_ID,
                UcetDal_ID,
                UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaDodacihoListuVydaneho WITH (NOLOCK)
   UNION SELECT ID,
                'PolozkaProdejkyPrijate' AS ObjectName,
                Root_ID,
                Nazev,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                DphZakladCM,
                CelkovaCena,
                CelkovaCenaCM,
                JednCena,
                JednCenaCM,
                Mnozstvi,
                Jednotka,
                Predkontace_ID,
                UcetDal_ID,
                UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaProdejkyPrijate WITH (NOLOCK)
   UNION SELECT ID,
                'PolozkaProdejkyVydane' AS ObjectName,
                Root_ID,
                Nazev,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                DphZakladCM,
                CelkovaCena,
                CelkovaCenaCM,
                JednCena,
                JednCenaCM,
                Mnozstvi,
                Jednotka,
                Predkontace_ID,
                UcetDal_ID,
                UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaProdejkyVydane WITH (NOLOCK)
   UNION SELECT ID,
                'PolozkaVyrobky' AS ObjectName,
                Root_ID,
                Nazev,
                Stredisko_ID,
                Zakazka_ID,
                Cinnost_ID,
                DphZakladCM,
                CelkovaCena,
                CelkovaCenaCM,
                JednCena,
                JednCenaCM,
                Mnozstvi,
                Jednotka,
                Predkontace_ID,
                UcetDal_ID,
                UcetMD_ID
   FROM dbo.SkladovyDoklad_PolozkaVyrobky WITH (NOLOCK)) AS Polozka ON Polozka.ID = Pohyb.Polozka_ID